def exception():
    raise ZeroDivisionError("Generated Exception")

exception()
